Minor improvements
This commit changes the installation path from /usr/bin to /usr/local/bin

diff --git a/extract b/extract
--- a/extract
+++ b/extract
@@ -5,8 +5,8 @@ if [[ $1 == "" ]]; then
     exit 1
 fi
 
-if [[ ! -f "/usr/bin/smv" ]]; then
-    echo "error: Could not find SmartVersion executable in /usr/bin."
+if [[ ! -f "/usr/local/bin/smv" ]]; then
+    echo "error: Could not find SmartVersion executable in /usr/local/bin."
     exit 1
 fi
 
@@ -15,9 +15,7 @@ if [[ ! -f "$1" ]]; then
     exit 1
 fi
 
-"/usr/bin/env" "smv" x $1 -br .
-
-if [[ $? != 0 ]]; then
+if ! "/usr/bin/env" "smv" x $1 -br .; then
     echo "error: Could not extract SmartVersion patch."
     exit 1
 fi
diff --git a/install-smartversion b/install-smartversion
--- a/install-smartversion
+++ b/install-smartversion
@@ -15,26 +15,20 @@ else
     exit 1
 fi
 
-wget "https://www.smartversion.com/smartvs38_linux_$CPU_ARCHITECTURE.zip" -O "smartvs38_linux_$CPU_ARCHITECTURE.zip"
-
-if [[ $? != 0 ]]; then
+if ! wget "https://www.smartversion.com/smartvs38_linux_$CPU_ARCHITECTURE.zip" -O "smartvs38_linux_$CPU_ARCHITECTURE.zip"; then
     echo "error: Could not download SmartVersion package."
     exit 1
 fi
 
-unzip -o "smartvs38_linux_$CPU_ARCHITECTURE.zip"
-
-if [[ $? != 0 ]]; then
+if ! unzip -o "smartvs38_linux_$CPU_ARCHITECTURE.zip"; then
     echo "error: Could not unzip SmartVersion package."
     exit 1
 fi
 
-cp "smv" "/usr/bin"
-
-if [[ $? != 0 ]]; then
-    echo "error: Could not copy SmartVersion executable to /usr/bin/smv."
+if ! cp "smv" "/usr/local/bin"; then
+    echo "error: Could not copy SmartVersion executable to /usr/local/bin/smv."
     exit 1
 fi
 
-echo "success: Successfully installed SmartVersion executable to /usr/bin/smv."
+echo "success: Successfully installed SmartVersion executable to /usr/local/bin/smv."
 exit 0
diff --git a/patch b/patch
--- a/patch
+++ b/patch
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
-if [[ ! -f "/usr/bin/smv" ]]; then
-    echo "error: Could not find SmartVersion executable in /usr/bin."
+if [[ ! -f "/usr/local/bin/smv" ]]; then
+    echo "error: Could not find SmartVersion executable in /usr/local/bin."
     exit 1
 fi
 
@@ -26,9 +26,7 @@ if [[ ! -f "$2" ]]; then
 fi
 
 # -nbhashbits 24 -compressratio 192: https://forums.mydigitallife.net/threads/smartversion-tools-scripts.79415/page-14#post-1599203
-"/usr/bin/env" "smv" BuildPatch "${1%.*}_to_${2%.*}.svf" $1 $2 -nbhashbits 24 -compressratio 192 -sha1 -sha256
-
-if [[ $? != 0 ]]; then
+if ! "/usr/bin/env" "smv" BuildPatch "${1%.*}_to_${2%.*}.svf" $1 $2 -nbhashbits 24 -compressratio 192 -sha1 -sha256; then
     echo "error: Could not patch files."
     exit 1
 fi
diff --git a/uninstall-smartversion b/uninstall-smartversion
--- a/uninstall-smartversion
+++ b/uninstall-smartversion
@@ -5,17 +5,15 @@ if [[ $EUID != 0 ]]; then
     exit 1
 fi
 
-if [[ ! -f "/usr/bin/smv" ]]; then
-    echo "error: Could not find SmartVersion executable in /usr/bin."
+if [[ ! -f "/usr/local/bin/smv" ]]; then
+    echo "error: Could not find SmartVersion executable in /usr/local/bin."
     exit 1
 fi
 
-rm "/usr/bin/smv"
-
-if [[ $? != 0 ]]; then
-    echo "error: Could not remove SmartVersion executable from /usr/bin/smv."
+if ! rm "/usr/local/bin/smv"; then
+    echo "error: Could not remove SmartVersion executable from /usr/local/bin/smv."
     exit 1
 fi
 
-echo "success: Successfully uninstalled SmartVersion executable from /usr/bin/smv."
+echo "success: Successfully uninstalled SmartVersion executable from /usr/local/bin/smv."
 exit 0
